// // app/layout.js or wherever your RootLayout is defined
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "./componants/Header";
// import Footer from "./componants/Footer";
// import 'antd/dist/reset.css'; // Ant Design styles

import MainLayoutComponant from "../componants/MainLayoutComponant";


// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Header/>
//         <main className="min-h-screen bg-gray-100 pt-16 pb-24">
//           {children}
//         </main>
//         <Footer />
//       </body>
//     </html>
//   );
// }





// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const RootLayout = ({ children }) => {
//   return (
//     <html lang="en">
//       <body>
//         <MainLayoutComponant>{children}</MainLayoutComponant>
//       </body>
//     </html>
//   );
// };

// export default RootLayout;


import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../componants/Header";
import CustomFooter from "../componants/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
        {children}
        <CustomFooter/>
        </body>
    </html>
  );
}
