import { Inter } from "next/font/google";
import '@/app/globals.css';
import SidebarWrapper from "../componants/SidebarWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trains-Cafe Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarWrapper>
          {children}
        </SidebarWrapper>
      </body>
    </html>
  );
}


