// "use client";
// import React from 'react';
// import { AntdRegistry } from '@ant-design/nextjs-registry';
// import CustomLayout from '@/app/componants/DashboardLayout';



// const RootLayout = ({ children }) => (
//   <html lang="en">
//     <body>
//       <AntdRegistry><CustomLayout> {children}</CustomLayout></AntdRegistry>
//     </body>
//   </html>
// );

// export default RootLayout;


"use client";
import { Inter } from "next/font/google";
// import "../globals.css";
import '@/app/globals.css'
import Layout, { Content, Footer } from "antd/es/layout/layout";
import Sidebar from "@/app/componants/Sidebar";
import DashHeader from "@/app/componants/DashHeader";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [collapsed, setCollapsed] = useState(false);

  const toggleCollapsed = () => {
    setCollapsed(!collapsed);
  };
  return (
    <html lang="en">
      <body className={inter.className}>
      <Layout style={{ minHeight: '100vh' }}>
      <Sidebar collapsed={collapsed} width={256} />
      <Layout className="site-layout">
        <DashHeader collapsed={collapsed} toggleCollapsed={toggleCollapsed} />
        <Content style={{ margin: '16px' }}>
          {children}
        </Content>

      </Layout>
    </Layout>
        </body>
    </html>
  );
}